In [ ]:
import pandas as pd

df= pd.read_csv('customer_data.csv')

df.head()

df.drop(columns=['CustomerID', 'Age', 'Gender'])

In [8]:
df.head()

,CustomerID,Age,Gender,Tenure,Usage Frequency,Support Calls,Payment Delay,Subscription Type,Contract Length,Total Spend,Last Interaction,Churn
0,2.0,30.0,Female,39.0,14.0,5.0,18.0,Standard,Annual,932.0,17.0,1.0
1,3.0,65.0,Female,49.0,1.0,10.0,8.0,Basic,Monthly,557.0,6.0,1.0
2,4.0,55.0,Female,14.0,4.0,6.0,18.0,Basic,Quarterly,185.0,3.0,1.0
3,5.0,58.0,Male,38.0,21.0,7.0,7.0,Standard,Monthly,396.0,29.0,1.0
4,6.0,23.0,Male,32.0,20.0,5.0,8.0,Basic,Monthly,617.0,20.0,1.0

In [19]:
df['Gender'].value_counts()

Gender
Male      250252
Female    190580
Name: count, dtype: int64

In [ ]:
df = pd.get_dummies(df,columns=['Gender','Contract Length'],drop_first=True)

In [23]:
df.head()

,Tenure,Usage Frequency,Support Calls,Payment Delay,Subscription Type,Total Spend,Last Interaction,Churn,Gender_Male,Contract Length_Monthly,Contract Length_Quarterly
0,39.0,14.0,5.0,18.0,Standard,932.0,17.0,1.0,False,False,False
1,49.0,1.0,10.0,8.0,Basic,557.0,6.0,1.0,False,True,False
2,14.0,4.0,6.0,18.0,Basic,185.0,3.0,1.0,False,False,True
3,38.0,21.0,7.0,7.0,Standard,396.0,29.0,1.0,True,True,False
4,32.0,20.0,5.0,8.0,Basic,617.0,20.0,1.0,True,True,False

In [24]:
X = df.drop(columns=['Exited'])
y = df['Exited'].values

KeyError: "['Exited'] not found in axis"